# Base config for listops

eval_frequency: 100
num_train_steps: 2501
num_eval_steps: 99999
checkpoint_freq: 1250

model_kwargs:
  emb_dim: 256
  num_heads: 4
  num_layers: 6
  qkv_dim: 256
  mlp_dim: 1024
  max_len: 2000
  classifier_pool: "CLS"
  num_classes: 10

data_kwargs:
  task_name: "basic"
  data_dir: "google_datasets/listops-1000/"
  batch_size: 16

optim_kwargs:
  lr_schedule_kwargs:
    warmup_steps: 500

task_type: "listops"
model_base: "encoder"
model_folder: "trained_models/listops"

