# Base config for text classification

eval_frequency: 200
num_train_steps: 20001
num_eval_steps: -1
checkpoint_freq: 4000

model_kwargs:
  emb_dim: 512
  num_heads: 8
  num_layers: 6
  qkv_dim: 512
  mlp_dim: 2048
  max_len: 1000
  classifier_pool: "CLS"
  num_classes: 2

data_kwargs:
  task_name: "imdb_reviews"
  data_dir: null
  num_data_entries: null
  batch_size: 32

optim_kwargs:
  lr_schedule_kwargs:
    warmup_steps: 8000

task_type: "text_classification"
model_base: "encoder"

