# Base config for text classification

batch_size: 32
eval_frequency: 100
num_train_steps: 5001
num_eval_steps: -1
learning_rate: 0.05
weight_decay: 0.1
max_target_length: 200
max_eval_target_length: 200
sampling_temperature: 0.6
sampling_top_k: 20
max_predict_token_length: 50
save_checkpoints: True
restore_checkpoints: True
checkpoint_freq: 2500
random_seed: 0
prompt: ""
factors: "constant * linear_warmup * rsqrt_decay"
warmup: 2000

base_type: "encoder"

model_kwargs:
  emb_dim: 256
  num_heads: 4
  num_layers: 6
  qkv_dim: 256
  mlp_dim: 1024
  max_len: 1000
  classifier_pool: "CLS"

num_data_entries: null

available_devices: [0,1,2,3]
task_name: "imdb_reviews"
data_dir: null

trial: 0  # dummy for repeated runs.

