batch_size: 32
eval_frequency: 100
num_train_steps: 5000
num_eval_steps: -1
learning_rate: 0.05
weight_decay: 0.1
max_target_length: 200  # ignored
max_eval_target_length: 200  # ignored
sampling_temperature: 0.6
sampling_top_k: 20
max_predict_token_length: 50
save_checkpoints: True
restore_checkpoints: True
checkpoint_freq: 10000
random_seed: 0
prompt: ""
factors: "constant * linear_warmup * rsqrt_decay"
warmup: 8000

tokenizer: "char"
base_type: "dual_encoder"

model_kwargs:
  emb_dim: 128
  num_heads: 4
  num_layers: 4
  qkv_dim: 128
  mlp_dim: 512
  max_len: 4000
  classifier_pool: "CLS"

vocab_file_path: "google_datasets/doc_retrieval/aan/"
task_name: "aan_pairs"
data_dir: "google_datasets/doc_retrieval/tsv_data/"
available_devices: [0,1,2,3]

trial: 0  # dummy for repeated runs.

