# Base config for matching

eval_frequency: 200
num_train_steps: 10001
num_eval_steps: -1
checkpoint_freq: 2000

model_kwargs:
  emb_dim: 128
  num_heads: 4
  num_layers: 4
  qkv_dim: 128
  mlp_dim: 512
  max_len: 4000
  classifier_pool: "CLS"
  num_classes: 2

data_kwargs:
  task_name: "aan_pairs"
  data_dir: "google_datasets/doc_retrieval/tsv_data/"
  vocab_file_path: "google_datasets/doc_retrieval/aan/"
  tokenizer: "char"
  batch_size: 32

optim_kwargs:
  lr_schedule_kwargs:
    warmup_steps: 8000

task_type: "matching"
model_base: "dual_encoder"

